### ISSUE TITLE
One Page

### ISSUE THREAD

**Issue by kpgardner** [kpgardner/rgb-game#3]
I want to make it so that each room is one page. How do I write a choice that displays the response on the same page instead of just linking to another page?

**Comment by chrisortman** [comment]
Andrew m is doing something very similar. What we did is in your view function pass a list tipped of (choice_text,url) and I'm the html file loop over those and generate one form per choice
The form uses the url for the action and the choice text to make a button. Then if you give each button name="choice" you can know which button was clicked with request.POST['choice']

**Comment by chrisortman** [comment]
Argh won't let me edit on phone. 
Above should say "list of tuples of (choice_text,url)"

**Comment by chrisortman** [comment]
@kpgardner 
Something I thought about with your game. You wouldn't have to have a separate class per room. If you have each room be a view function. 
You can put functions in views.py that aren't view functions. Think of them as helper functions
So if you could write a function that takes a list of choices and returns a list of texts you'd be almost there.
